### ISSUE TITLE
[FEATURE]: Auto-update changelog

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#658]
### Describe the solution you are looking for

For reference - after deleting plugwise/testchange

### Describe alternatives you've considered

Github workflow considered:

```
jobs:
  build:
    name: Create release with release notes from changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CSchoel/release-notes-from-changelog@v1
      # use GitHub CLI to create release
      # see https://cli.github.com/manual/gh_release_create
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -p
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
```

### What type of installation are you running?

Home Assistant OS

### How did you install python-plugwise (or `plugwise`) for short

Other use (installed using `pip`)

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

na

### Your setup

na

### Additional context

na
